In [37]:
import torch
import numpy as np

- Everything in pytorch is based on Tensor operations.
- A tensor can have different dimensions
- so it can be 1d, 2d, or even 3d and higher

- scalar, vector, matrix, tensor

In [2]:
# create an empty tensors:
# torch.empty(size): uninitiallized
x = torch.empty(1) # 1 is size # scalar
print(x)

tensor([0.])


In [3]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([0., 0., 0.])


In [4]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[8.4338e+26, 1.9418e+20, 5.0432e-14],
        [1.3563e-19, 1.7753e+28, 1.3458e-14]])


In [5]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [7]:
# torch.rand(size): random numbers between [0, 1] with size 5 * 3
x = torch.rand(5, 3)
print(x)

tensor([[0.5758, 0.8257, 0.4041],
        [0.9028, 0.3267, 0.2167],
        [0.7940, 0.0371, 0.1514],
        [0.1893, 0.1476, 0.6615],
        [0.3602, 0.2483, 0.8880]])


In [8]:
x = torch.rand(2, 2)
print(x)

tensor([[0.6156, 0.1992],
        [0.5431, 0.7213]])


In [9]:
# torch.zeros(size), fill with 0
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [10]:
# torch.ones(size), fill with 1
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [11]:
# check data type
print(x.dtype)

torch.float32


In [14]:
# we can also give dtype as a parameter
x = torch.ones(2, 2, dtype=torch.int)
print(x)
print(x.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32


In [15]:
x = torch.ones(2, 2, dtype=torch.double)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
torch.float64


In [16]:
x = torch.ones(2, 2, dtype=torch.float16)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
torch.float16


In [17]:
x = torch.ones(2, 2, dtype=torch.int16)
print(x)
print(x.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int16)
torch.int16


In [18]:
x = torch.ones(2, 2, dtype=torch.int8)
print(x)
print(x.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)
torch.int8


In [19]:
# check size
print(x.size())

torch.Size([2, 2])


In [20]:
# construct tensor from data, let's say python list
x = torch.tensor([5.5, 3])
print(x.size())
print(x)

torch.Size([2])
tensor([5.5000, 3.0000])


## Basic Operations

In [21]:
# Operations
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.1528, 0.2348],
        [0.0020, 0.5168]])
tensor([[0.3926, 0.4325],
        [0.2473, 0.2087]])


In [22]:
# elementwise addition
z = x + y
print(z)

tensor([[0.5454, 0.6673],
        [0.2493, 0.7255]])


In [23]:
z = torch.add(x,y) # Do same as above operations
print(z)

tensor([[0.5454, 0.6673],
        [0.2493, 0.7255]])


In [24]:
# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.1528, 0.2348],
        [0.0020, 0.5168]])
tensor([[0.3926, 0.4325],
        [0.2473, 0.2087]])
tensor([[0.5454, 0.6673],
        [0.2493, 0.7255]])


In [25]:
# substraction
z = x - y
print(z)
z = torch.sub(x, y)
print(z)

tensor([[-0.3926, -0.4325],
        [-0.2473, -0.2087]])
tensor([[-0.3926, -0.4325],
        [-0.2473, -0.2087]])


In [30]:
# multiplication
z = x * y
print(z)
z = torch.mul(x,y)
print(z)
y.mul_(x)
print(y)

tensor([[0.0833, 0.1567],
        [0.0005, 0.3749]])
tensor([[0.0833, 0.1567],
        [0.0005, 0.3749]])
tensor([[0.0833, 0.1567],
        [0.0005, 0.3749]])


In [31]:
# division
z = x / y
print(z)
z = torch.div(x,y)
print(z)

tensor([[1.8336, 1.4986],
        [4.0107, 1.3783]])
tensor([[1.8336, 1.4986],
        [4.0107, 1.3783]])


In [32]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.4910, 0.6875, 0.1019],
        [0.0263, 0.7084, 0.2806],
        [0.5892, 0.8952, 0.7014],
        [0.7086, 0.6149, 0.2118],
        [0.9542, 0.9215, 0.7140]])
tensor([0.4910, 0.0263, 0.5892, 0.7086, 0.9542])
tensor([0.0263, 0.7084, 0.2806])
tensor(0.7084)


In [33]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.7084102630615234


In [34]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [35]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [38]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [39]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
# again be careful when modifying
a += 1
print(a)
print(b)

In [41]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    z = z.numpy()

In [42]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)
